name: Generate documentation

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
            doxyfile-path: ./doc/Doxygen/Doxyfile
            working-directory: ./doc/Doxygen

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: page
