name: Generate documentation

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt install -y doxygen

      - name: Generate
        run: |
          cd doc/Doxygen
          doxygen doc/Doxygen/Doxyfile
